//user

export const SET_USER = "SET_USER";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOG_OUT = "LOG_OUT";
export const UPDATE_USER = "UPDATE_USER";

//users
export const FETCH_USER = "FETCH_USER";
export const FETCH_USERS = "FETCH_USERS";
export const ADD_USER = "ADD_USER";
export const ADD_USERS = "ADD_USERS";
export const SET_USERS = "SET_USERS";
export const CLEAR_USERS = "CLEAR_USERS";
export const SET_SEARCH_USERS = "SET_SEARCH_USERS";
export const CLEAR_SEARCH_USERS = "CLEAR_SEARCH_USERS";

//household
export const CREATE_NEW_HOUSEHOLD = "CREATE_NEW_HOUSEHOLD";
export const UPDATE_HOUSEHOLD_DESCRIPTION = "CREATE_HOUSEHOLD_DESCRIPTION";
export const ADD_USER_TO_HOUSEHOLD = "ADD_USER_TO_HOUSEHOLD";
export const REMOVE_USER_FROM_HOUSEHOLD = "REMOVE_USER_FROM_HOUSEHOLD";
export const ADD_HOUSEHOLD_PRODUCT = "ADD_HOUSEHOLD_PRODUCT";
export const REMOVE_HOUSEHOLD_PRODUCT = "REMOVE_HOUSEHOLD_PRODUCT";
export const REMOVE_HOUSEHOLD = "REMOVE_HOUSEHOLD";

//households
export const FETCH_HOUSEHOLDS = "FETCH_HOUSEHOLDS";
export const FETCH_HOUSEHOLD = "FETCH_HOUSEHOLD";
export const FETCH_OWNER_HOUSEHOLDS = "FETCH_OWNER_HOUSEHOLDS";
export const FETCH_USER_HOUSEHOLDS = "FETCH_USER_HOUSEHOLDS";
export const ADD_HOUSEHOLD_TO_USER_HOUSEHOLDS = "ADD_HOUSEHOLD";
export const SET_USER_HOUSEHOLDS = "SET_USER_HOUSEHOLDS";
export const SET_SELECTED_HOUSEHOLD = "SET_SELECTED_HOUSEHOLD";
export const CLEAR_USER_HOUSEHOLDS = "CLEAR_USER_HOUSEHOLDS";
